### ISSUE TITLE
No module named 'milvus_database'

### ISSUE THREAD

**Issue by LeiyanGithub** [HowieHwong/MetaTool#1]
hello, how can I solve the problem of "No module named 'milvus_database'"?

**Comment by LeiyanGithub** [comment]
hello, May I ask you how to solve this problem?
<img width="903" alt="image" src="https://github.com/HowieHwong/MetaTool/assets/45895439/58a4a15a-ed0d-4ea9-9f94-3a8bdd5cee18">

**Comment by HowieHwong** [comment]
I'm sorry for the late reply. you can import milvus_database.py from src/embedding/.

**Comment by HowieHwong** [comment]
I've never seen this error and I suggest you refer to milvus docs to figure out this problem.
