### ISSUE TITLE
Could you provide dataset with conversation format?

### ISSUE THREAD

**Issue by ZijunSong** [HowieHwong/MetaTool#12]
Hello! I apologize for the interruption and thank you for your work on this project.

I noticed that you have provided a tmp_dataset, where each data entry includes thought_prompt, label, tool, and query. However, this format differs from the typical conversational format we use when interacting with GPT. I was wondering if the project could support conversational data, such as the ShareGPT format, to facilitate fine-tuning of large language models?

Additionally, would it be possible to provide an evaluation method for the dataset?

Thank you very much for your time and assistance!

**Comment by HowieHwong** [comment]
Hi,

Thanks for your feedback. I think you can use a fine-tuning toolkit like Llama-factory to process with it. It can be easily processed in a script.
