### ISSUE TITLE
pymilvus.exceptions.SchemaNotReadyException

### ISSUE THREAD

**Issue by cp-jose** [HowieHwong/MetaTool#2]
hello. I noticed a few imprecisions on the README, but managed to get to the part where (after installing and starting a local milvus standalone) I attempt to construct the prompts using `python prompt_constructing.py all` which yields this error:

    raise SchemaNotReadyException(
    pymilvus.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=1, message=Collection 'tool_embedding' not exist,     or you can pass in schema to create one.)>

Since no specific version for pymilvus is specified on the `requirements.txt` file I have installed version `'2.3.5'`. 

Can you please advise on how to overcome this? 

thank you

**Comment by HowieHwong** [comment]
Hi! For the error:
```python
raise SchemaNotReadyException(
pymilvus.exceptions.SchemaNotReadyException: <SchemaNotReadyException: (code=1, message=Collection 'tool_embedding' not exist,     or you can pass in schema to create one.)>
```
You should firstly run `milvus_database.py` to construct a Collection.

Sorry for ambiguous version of `milvus`. I've checked it and it's `2.2.15` in my device.

**Comment by cp-jose** [comment]
thanks for the prompt reply. Issue closed.
