### ISSUE TITLE
wrong paths on the code

### ISSUE THREAD

**Issue by cp-jose** [HowieHwong/MetaTool#3]
There are many paths that don't match between code and repository. I've been fixing the ones that are obvious, but can't seem to find this one `'../prompt_data/general_test.json'`. What does this refer to, and where can it be found?

**Comment by HowieHwong** [comment]
> There are many paths that don't match between code and repository. I've been fixing the ones that are obvious, but can't seem to find this one `'../prompt_data/general_test.json'`. What does this refer to, and where can it be found?

Sorry for the late reply. `'../prompt_data/general_test.json'` is generated by `prompt_construction.py` and you should firstly run it.

**Comment by cp-jose** [comment]
OK. The problem is the directories have wrong names, and the code isn't running because of that. You may want to fix that. `'prompt_data'` directory does not exist, and must be created. 
I ran `'python prompt_construction.py similar'` successfully now and the file `'../prompt_data/general_test.json'` was generated (after creating the hosting directory).

I'm now trying to run `'python prompt_construction.py all'` and it is breaking at: 
`FileNotFoundError: [Errno 2] No such file or directory: '../prompt/multi_tool_selection'`

**Comment by HowieHwong** [comment]
It's `../prompt/multi_tool_selection.json`. I will fixed them ASAP.

**Comment by cp-jose** [comment]
i'm afraid that file doesn't exist either. Would that be `'./dataset/data/multi_tool_query_golden.json'` instead?
