### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tool/test_data/vicuna-7b'

### ISSUE THREAD

**Issue by sian-chen** [HowieHwong/MetaTool#6]
Dear Authors,

In `src/generation/run.py`, there are many places requiring data from `tool/test_data` or `tool/new_test_res`.
But these data are neither provided in the repository nor generated after prompt construction.
Could you please confirm where can we access the data?
Thanks.

**Comment by HowieHwong** [comment]
Dear Sian,

The file path can be defined by yourself. What you need to do is replace it with your file path of the dataset. I will update is in README.md ASAP.

**Comment by sian-chen** [comment]
Hi @HowieHwong,

Could you explain more about which file should we use?
It is the file generated by `prompt_construction.py`?
It would be very helpful if there are some scripts to reproduce the results in the paper.
Thanks!

**Comment by HowieHwong** [comment]
Yes. That's it.

> Hi @HowieHwong,
> 
> Could you explain more about which file should we use? It is the file generated by `prompt_construction.py`? It would be very helpful if there are some scripts to reproduce the results in the paper. Thanks!

**Comment by HowieHwong** [comment]
Moreover, I have uploaded the datasets in dataset/tmp_dataset. You can check about it.

> Hi @HowieHwong,
> 
> Could you explain more about which file should we use? It is the file generated by `prompt_construction.py`? It would be very helpful if there are some scripts to reproduce the results in the paper. Thanks!

**Comment by wenjunli-0** [comment]
> Moreover, I have uploaded the datasets in dataset/tmp_dataset. You can check about it.
> 
> > Hi @HowieHwong,
> > Could you explain more about which file should we use? It is the file generated by `prompt_construction.py`? It would be very helpful if there are some scripts to reproduce the results in the paper. Thanks!

Hi @HowieHwong, thanks for the excellent work.

Can you give a specific setting for `tool/test_data` and `tool/new_test_res/`? 

I saw your updated files in `dataset/tmp_dataset/`, but there are also .json files (under `/prompt_data/`) generated by prompt_construction.py. So I am a bit confused about how to map `tool/test_data` and `tool/new_test_res/` to the new directories.

**Comment by HowieHwong** [comment]
> > Moreover, I have uploaded the datasets in dataset/tmp_dataset. You can check about it.
> > > Hi @HowieHwong,
> > > Could you explain more about which file should we use? It is the file generated by `prompt_construction.py`? It would be very helpful if there are some scripts to reproduce the results in the paper. Thanks!
> 
> Hi @HowieHwong, thanks for the excellent work.
> 
> Can you give a specific setting for `tool/test_data` and `tool/new_test_res/`?
> 
> I saw your updated files in `dataset/tmp_dataset/`, but there are also .json files (under `/prompt_data/`) generated by prompt_construction.py. So I am a bit confused about how to map `tool/test_data` and `tool/new_test_res/` to the new directories.

Hi Wenjun,

You can manually create the dictionary in your project. Since the time is a bit distant, one possible is that the two of them are the same dict. This may be due to my handwriting the wrong code.
